# Calcul matriciel

Très présentes en mathématiques, les matrices sont un moyen pratique de présenter des données et d'en tirer des informations importantes. Leurs premiers utilisations se faisaient dans le cadre de l'algèbre linéaire mais au fil des années, elles ont pris une place de plus en plus importante dans des domaines comme la statistique ou la théorie des graphes.

## Les matrices

Les matrices permettent de simplifier la présentation d'un tableau à double entrée. Bien qu'utilisées avant lui, c'est **James Joseph Sylvester** qui les nomma ainsi en 1850 dans la mesure où elles donnent naissance à des familles de déterminants associés.

### L'ensemble $M_{n, p}(K)$
Dans ce qui suit, $n$ et $p$ sont des entiers strictement positifs et $K$ designe une structure algébrique (un ensemble de nombres) vérifiant des propriétés particulières. $K$ pourra par exemple être l'ensemble $\mathbb{R}$ des réels ou $\{0, 1\}$.

**Définition**  
* Une **matrice** de dimension $(n, p)$ ou $n \times p$ à coefficients dans $K$ est un tableau de $n$ lignes et $p$ colonnes d'éléments de $K$.
* $M_{n, p}(K)$ désigne l'ensemble de ces matrices.

Quelques matrices particulières portent des noms bien définis:
* Si $n=1$, alors la matrice est une **matrice ligne**.
* Si $p=1$, alors la matrice est une **matrice colonne**.
* Si $n=p$, alors la matrice est une **matrice carrée** de dimension $n$

Pour les calculs matriciels en Python, nous importons le module **numpy** avec la commmande suivante:

In [1]:
import numpy as np

Voici une matrice $2 \times 3$ avec des coefficients entiers.

In [5]:
A = np.array([[1, 2, 3], [-1, 1, 4]])
print(A)

[[ 1  2  3]
 [-1  1  4]]


Voici une matrice carré $2 \times 2$ avec des coefficients réels.

In [8]:
B = np.array([[0, 4], [3.2, np.pi]])
print(B)

[[0.         4.        ]
 [3.2        3.14159265]]


Voici une matrice colonne $3 \times 1$ avec des coefficients réels.

In [11]:
C = np.array([[1], [3], [-7.8]])
print(C)

[[ 1. ]
 [ 3. ]
 [-7.8]]


### Indexation des coefficients et transposé
Le coefficient d'une matrice $A \in M_{n, p}(\mathbb{R})$ situé à la i-ème ligne et à la j-ème colonne se note $a_{i, j}$.

La matrice $A$ peut s'écrire
$$ (a_{i, j})_{0 \le i \lt n, 0 \le j \lt p} $$

**Définition**  
Lorsque  $A \in M_{n, p}(K)$, la **transposée** de $A$ notée $A^t$ est la matrice $M_{p, n}(K)$, telle que $a_{i, j}^t = a_{j, i}$

En **numpy** la méthode `transpose()` transforme une matrice en sa transposé.

In [18]:
A.transpose()

array([[ 1, -1],
       [ 2,  1],
       [ 3,  4]])

In [16]:
B.transpose()

array([[0.        , 3.2       ],
       [4.        , 3.14159265]])

La transposé d'une matrice colonne est une matrice ligne.

In [17]:
C.transpose()

array([[ 1. ,  3. , -7.8]])

### Cas particuliers des matrices carrées
Dans cette section $A$ est une matrice carrée de dimension $n > 0$ à coefficients dans $\mathbb{R}$.

La diagonale de la matrice $A$ est l'ensemble de ses coefficients qui sont de la forme $a_{i, i}$ c'est-à-dire l'ensemble des nombres situes sur la diagonale allant du haut à gauche vers le bas à droite.

#### Matrice triangulaire
A est une matrice **triangulaire supérieur** si tous ses éléments situés sals la diagonale sont nuls c'est-à-dire si 
$$ i>j \implies a_{i, j}=0 $$

Exemple:

In [21]:
A = np.array([[1, 2, 7], [0, 1, 4], [0, 0, 5]])
print(A)

[[1 2 7]
 [0 1 4]
 [0 0 5]]


$A$ est une matrice **triangulaire inférieure** si tous ses éléments situés au-dessus de la diagonale sont nuls c'est-à-dire si 
$$ i<j \implies a_{i, j}=0 $$

Exemple:

In [24]:
B = np.array([[1, 0, 0], [5, 1, 0], [2, 9, 5]])
print(B)

[[1 0 0]
 [5 1 0]
 [2 9 5]]


#### Matrice diagonale
$A$ est une matrice **diagonale** si tous ses éléments situés au-dessus de la diagonale sont nuls c'est-à-dire si 
$$ i \neq j \implies a_{i, j}=0 $$

Exemple:

In [25]:
D = np.array([[1, 0, 0], [0, 5, 0], [0, 0, 9]])
print(D)

[[1 0 0]
 [0 5 0]
 [0 0 9]]


Parmis les matrices diagonales de $M_n (\mathbb{R})$, la matrice ne présentant que des 1 sur al diagonale est la matrice identié. Elle est noté $I_n$ et elle possède un rôle bien particulier.

In [33]:
I = np.identity(3, dtype='int')
print(I)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


#### Matrice symétrique
$A$ est une matrice **symétrique** si $A^t = A$, c'est-à-dire si 

Exemple:

In [27]:
D = np.array([[-1, 1, 3], [1, 4, 0], [3, 0, 7]])
print(D)

[[-1  1  3]
 [ 1  4  0]
 [ 3  0  7]]


## Le calcul matriciel
Dans cette section nous allons détailler les règles du calcul matriciel. Si l'addition de deux matrices et la multiplication d'une matrice par une constante sont des opérations assez intuitives, il n'en est pas de même pour le produit matriciel.

### Somme et différence de deux matrices

La somme de deux matrices $S = A + B$ est obtenu en additionnant les coefficients correspondants
$$ s_{i,j} = a_{i,j} + b_{i,j} $$

In [42]:
A = np.array([[1, 2, 9], [-7, 0, 8]])
print(A)

[[ 1  2  9]
 [-7  0  8]]


In [37]:
B = np.array([[5, 4, -1], [-2, 3, 0]])
print(B)

[[ 5  4 -1]
 [-2  3  0]]


In [44]:
S = A + B
print(S)

[[ 6  6  8]
 [-9  3  8]]


La différence de deux matrices $S = A - B$ est obtenu en soustrayant les coefficients correspondants
$$ d_{i,j} = a_{i,j} - b_{i,j} $$

In [45]:
D = A - B
print(D)

[[-4 -2 10]
 [-5 -3  8]]


**Propriété**  
* L'addition est **commutative**: $A + B = B + A$
* L'addition est **transitive**: $(A + B) + C = A + (B + C)$  
* La matrice **nulle** noté 0 qui ne contient que des zéros est l'**élément neutre** de l'addition et de la soustraction.

In [49]:
Z = np.zeros((2, 3))
print(Z)

[[0. 0. 0.]
 [0. 0. 0.]]


In [53]:
print(A + Z == A)

[[ True  True  True]
 [ True  True  True]]


In [57]:
print(B - Z == B)

[[ True  True  True]
 [ True  True  True]]


### Multiplication d'une matrice par un nombre
Le produit d'une matrice A avec un scalaire $P = kA $ est obtenu en multipliant tous les coefficients par $k$.
$$ p_{i,j} = k a_{i,j}$$

In [61]:
P = 2 * A
print(P)

[[  2   4  18]
 [-14   0  16]]


### Produit de deux matrices
La multiplication de deux matrices est un peu plus complexe à mettre en oeuvre et n'est pas toujours possible. Pour pouvoir calculer $A \times B$ il faut que ne nombre de colonne de $A$ soit égale au nombre de lignes de $B$.

$$ c_{i, j} = \sum_{k=0}^{p-1} a_{i, k} \times b_{k, j} $$

In [63]:
A = np.array([[1, 2, 9], [-7, 0, 8]])
print(A)

[[ 1  2  9]
 [-7  0  8]]


In [64]:
B = np.array([[5, 4, -1], [-2, 3, 0], [1, 7, -2]])
print(B)

[[ 5  4 -1]
 [-2  3  0]
 [ 1  7 -2]]


In [69]:
M = np.matmul(A, B)
print(M)

[[ 10  73 -19]
 [-27  28  -9]]


**Propriété**  
* La multiplication n'est **pas commutative**: $A \times B \neq B \times A$ en général
* La multiplication est **associative**: $(A \times B) \times C = A \times (B \times C)$
* La matrice identité est l'**élément neutre** de la multiplication: $I_n \times A = A \times I_p = A$
* La multiplication est **distributive** par rapport à l'addition: $A \times (B + C) = A \times B + A \times C$ 


### La matrice identié
La matrice identité est l'élément neutre de la multiplication.

In [76]:
I2 = np.identity(2, dtype=int)
print(I2)

[[1 0]
 [0 1]]


In [77]:
I3 = np.identity(3, dtype=int)
print(I3)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [78]:
np.matmul(I2, A)

array([[ 1,  2,  9],
       [-7,  0,  8]])

In [79]:
np.matmul(A, I3)

array([[ 1,  2,  9],
       [-7,  0,  8]])

## Le cas particulier des matrices booléennes
En utilisant des matrices booléennes, on a l'ensemble $K=\{0, 1\}$. Les sommes de matrices deviennent des sommes booléennes et les produits des produits booléens.
Bien sûr la soustraction et la multiplication par un nombre différent de 0 ou de 1 n'ont plus de sens.

In [164]:
A = np.array([[1, 0, 0], [1, 1, 1], [0, 1, 1]], dtype=bool)
print(A*1)

[[1 0 0]
 [1 1 1]
 [0 1 1]]


In [165]:
B = np.array([[0, 1, 1], [1, 0, 1], [0, 0, 1]], dtype=bool)
print(B*1)

[[0 1 1]
 [1 0 1]
 [0 0 1]]


Alors la somme des deux matrices $A+B$ 

In [171]:
print((A+B)*1)

[[1 1 1]
 [1 1 1]
 [0 1 1]]


Ainsi que le produit $A \times B$

In [176]:
print(np.matmul(A, B)*1)

[[0 1 1]
 [1 1 1]
 [1 0 1]]


Les matrices booléennes sotn utiles par exemple dans l'étude des relations au sein d'un ensemble. Plutôt que de représenter une reation $R$ à l'aide d'un diagramme cartésien, on utilisera une matrice booléenne, les 1 correspondant aux cases cochées du diagramme. Plus précisement, si la matrice booléenne $A$ de dimension $n$ représente la relation $R$ su un ensemble $E=\{e_1, e_2, ... e_n\}$ alors $a_{i, j}$ vaut 1 lorsque $R(e_i, e_j)$ et 0 sinon.

In [177]:
E = {1, 2, 3, 4}

def R1(a, b):
    return a < b

def R2(a, b):
    return (a + b) % 2 == 0

In [185]:
A = np.fromfunction(R1, (5, 5))
print(A * 1)

[[0 1 1 1 1]
 [0 0 1 1 1]
 [0 0 0 1 1]
 [0 0 0 0 1]
 [0 0 0 0 0]]


In [184]:
B = np.fromfunction(R2, (5, 5))
print(B * 1)

[[1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]]


**Propriétés**  
* $R$ est réflexive si $A$ comporte uniquement des 1 sur sa diagonale ce qui se traduit par $A \ge I_n$
* $R$ est symétrique ou antisymetrique si $A$ l'est
* $R$ est transitive sur $A \ge A^2$

$A \ge A^2$ signifie que les coefficients de $A$ sont supérieur ou égaux aux coefficents de $A^2$ correspondants.
La dernière propriété apporte un vrai plus car elle fournit un moyen vraiment efficace permettant de vérifier rapidement le caractère transitif d'une relation.

In [189]:
print(np.matmul(A, A)*1)

[[0 0 1 1 1]
 [0 0 0 1 1]
 [0 0 0 0 1]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [190]:
print(np.matmul(B, B)*1)

[[1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]]


## Exercices

### Exercice 1 - coefficient général
Représenter les matrices carrées de dimension 4 dont le coefficient général est donnée par 
* $a_{i, j} = i + j$
* $b_{i, j} = (-1)^{i + j}$
* $c_{i, j} = a_{i, j} + b_{i, j}$

Remarque : les indices de Python commencent à zéro : $i, j \in \{0, 1, 2, 3\}$

In [193]:
A = np.fromfunction(lambda i, j: i + j, (4, 4), dtype=int)
print(A)

[[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]]


In [194]:
B = np.fromfunction(lambda i, j: (-1)**(i + j), (4, 4), dtype=int)
print(B)

[[ 1 -1  1 -1]
 [-1  1 -1  1]
 [ 1 -1  1 -1]
 [-1  1 -1  1]]


In [198]:
C = A + B
print(C)

[[1 0 3 2]
 [0 3 2 5]
 [3 2 5 4]
 [2 5 4 7]]


### Exercice 2 - matrice carrée
Donner une matrice carrée de dimension 3 qui, quand on l'ajoute à sa transposé, donne la matrice identité.

In [200]:
A = np.array([[.5, 1, 1], [-1, 0.5, 1], [-1, -1, 0.5]])
print(A)

[[ 0.5  1.   1. ]
 [-1.   0.5  1. ]
 [-1.  -1.   0.5]]


In [201]:
print(A + A.transpose())

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Exercice 3 - matrice antisymétrique
Que valent forcément les coefficients d'une matrice carrée antisymétrique ?

Pour les coefficients de la diagonale : $a_{i, i} = -a_{i, i}$, donc ils sont zéro.

### Exercice 4 - propriétés des matrices
Donner une matrice carrée de dimension 3 qui soit à la fois:
1. symétrique et antisymétrique
1. triangulaire supérieure et inférieure
1. antisymétrique et triangulaire inférieure

Symétrique et antisymétrique:  
$a_{i, j} = a_{j, i} = -a_{j, i}$  
c'est donc la matrice nulle

In [206]:
A = np.zeros((3, 3))
print(A)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Triangulaire supérieure et inférieure:  
c'est donc une matrice diagonale

In [210]:
B = np.diag([1, 2, 3])
print(B)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


Antisymétrique et triangulaire inférieure:  
c'est donc une matrice nulle.

In [206]:
A = np.zeros((3, 3))
print(A)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### Exercice 5 - multiplication
Soient les matrices suivantes:

In [211]:
A = np.array([[1, 2, 3], [0, 1, 3]])
print(A)

[[1 2 3]
 [0 1 3]]


In [212]:
B = np.array([[3, 1, 0], [-1, 1, 2], [0, 1, 1]])
print(B)

[[ 3  1  0]
 [-1  1  2]
 [ 0  1  1]]


In [213]:
C = np.array([[2], [1]])
print(C)

[[2]
 [1]]


In [215]:
D = np.array([[1, 2, 3]])
print(D)

[[1 2 3]]


In [216]:
E = np.array([[1], [0], [-1]])
print(E)

[[ 1]
 [ 0]
 [-1]]


In [218]:
F = np.array([[1, -1], [-1, 1]])
print(F)

[[ 1 -1]
 [-1  1]]


In [219]:
print(np.matmul(D, E))

[[-2]]


In [220]:
print(np.matmul(E, D))

[[ 1  2  3]
 [ 0  0  0]
 [-1 -2 -3]]


In [224]:
print(np.matmul(np.matmul(A, E), D))

[[-2 -4 -6]
 [-3 -6 -9]]


In [226]:
print(np.matmul(np.matmul(np.matmul(F, C), D), B))

[[ 1  6  7]
 [-1 -6 -7]]


In [228]:
#print(np.matmul(np.matmul(np.matmul(B, E), C), D)) #error: shapes not aligned

### Exercice 6 - distributivité
Soient les matrices $A$, $B$ et $C$.  
Vérifier que $(A+B) \times C = A \times C + B \times C$

In [250]:
A = np.array([[1, 2], [4, -1]])
B = np.array([[0, 3], [-7, 5]])
C = np.array([[1, 0], [2, -2]])

In [252]:
print(np.matmul(A + B, C))

[[ 11 -10]
 [  5  -8]]


In [255]:
print(np.matmul(A, C) + np.matmul(B, C))

[[ 11 -10]
 [  5  -8]]


In [262]:
(np.matmul(A + B, C) == np.matmul(A, C) + np.matmul(B, C)).all()

True

### Exercice 7

### Exercice 8 - commutativité
Donner deux matrices carrées $A$ et $B$ de dimension 2 telles que $A \times B = 0$ et $B \times A \neq 0$

In [278]:
A = np.array([[1, 1], [2, 2]])
print(A)

[[1 1]
 [2 2]]


In [281]:
B = np.array([[1, -1], [-1, 1]])
print(B)

[[ 1 -1]
 [-1  1]]


In [282]:
np.matmul(A, B)

array([[0, 0],
       [0, 0]])

In [283]:
np.matmul(B, A)

array([[-1, -1],
       [ 1,  1]])

### Exercice 9 - coûts de véhicule
Un artisan a besoin de louer un véhicule pendant 4 jours pour effectuer au total 500 km. Il a le choix entre trois loueurs dont les tarifs sont les suivants:
* loueur A: 70 Euros par jour
* loueur B: 50 centimes par km parcouru
* loueur C: 40 Euros par jour plus 40 centimes par km parcouru

Ecrire deux matrices ayant pour produit une matrice colonne contenant les montants que devrait payer l'artisan.  
Quel loueur a-t-il intérêt à choisir

In [300]:
A = np.array([[70, 0], [0, 0.5], [40, 0.4]])
B = np.array([[4], [500]])

C = np.matmul(A,B)
print(C)

[[280.]
 [250.]
 [360.]]


Il devrait choisir loueur B

### Exercice 10 - coûts de jouets
Reprenons l'entreprise du début de ce chaptire. Elle fabrique trois types de jouets en bois pour lesquels on dispose des informations suivantes: 

| -  | Main d'oevre (heures) | Bois (cubes) | Peinture (litres) |
|---|--------------------------|-----------------|----------------------|
| Jouet A | 2   | 1  | 2  |
| Jouet B | 2.5 | 4  | 4  |
| Jouet C | 1.5 | 3  | 2.5|

On sait de plus que les coûts pour l'entreprise sont de 30 Euros pour l'heure de main d'oeuvre, 10 Euro par cube de bois et 15 Euros par littre de peinture.

On pose:

In [238]:
A = np.array([[2, 1, 2], [2.5, 4, 4], [1.5, 3, 2.5]])
print(A)

[[2.  1.  2. ]
 [2.5 4.  4. ]
 [1.5 3.  2.5]]


In [245]:
Cost = np.array([[30], [10], [15]])
print(Cost)

[[30]
 [10]
 [15]]


In [240]:
Quantity = np.array([100, 200, 150])
print(Quantity)

[100 200 150]


In [248]:
# Unitary cost per toy
D = np.matmul(A, Cost)
print(D)

[[100. ]
 [175. ]
 [112.5]]


In [243]:
# Total resources consumed
print(np.matmul(Quantity, A))

[ 925. 1350. 1375.]


In [249]:
# Total cost
print(np.matmul(Quantity, D))

[61875.]


### Exercice 11

### Exercice 12

### Exercice 13

### Exercice 14 - puissance
Soit la matrice booléenne

$A=
\begin{pmatrix} 
0 & 1 & 1 \\
1 & 0 & 1 \\
1 & 1 & 0 \\
\end{pmatrix}
$

Calculer $A^n$ pour tout entier $n$ strictement positif lorsque le produit est le produit classique et lorsque le produit est le produit booléen.

In [310]:
A = np.array([[0, 1, 1], [1, 0, 1], [1, 1, 0]])
print(A)

[[0 1 1]
 [1 0 1]
 [1 1 0]]


In [311]:
B = A
for i in range(2, 6):
    print('n =', i)
    B = np.matmul(B, A)
    print(B)
    print()

n = 2
[[2 1 1]
 [1 2 1]
 [1 1 2]]

n = 3
[[2 3 3]
 [3 2 3]
 [3 3 2]]

n = 4
[[6 5 5]
 [5 6 5]
 [5 5 6]]

n = 5
[[10 11 11]
 [11 10 11]
 [11 11 10]]



In [308]:
A = np.array([[0, 1, 1], [1, 0, 1], [1, 1, 0]], dtype=bool)
B = A
for i in range(2, 5):
    print('n =', i)
    B = np.matmul(B, A)
    print(B *1)
    print()

n = 2
[[1 1 1]
 [1 1 1]
 [1 1 1]]

n = 3
[[1 1 1]
 [1 1 1]
 [1 1 1]]

n = 4
[[1 1 1]
 [1 1 1]
 [1 1 1]]

